conference:
  name: "ICML"
  year: 2024
  selections: ["oral", "spotlight", "poster"]

page_indicators:
  oral: 9
  spotlight: 11
  poster: 13

navigation_paths:
  base_url: "https://openreview.net/group?id={name}.cc/{year}/Conference#tab-accept-{selection}"
  next_page: "//*[@id='accept-{selection}']/div/div/nav/ul/li[{page_indicator}]/a"
  papers: "//*[@id='accept-{selection}']/div/div/ul/li"

save_info:
  save_dir: "outputs/{name}-{year}"
  save_filename: "{selection}_paper.json"
